---

- hosts: xenials
  become_user: root
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install base packages
      apt: name={{ item }} update_cache=yes
      with_items:
        "{{ base_packages }}"

    - name: Install pip requirements
      pip:
        name: "{{ item }}"
        state: latest
        executable: "{{ pip_exec }}"
      with_items:
        "{{ pip_packages }}"
