---

- name: install python2
  hosts: all
  become_user: root
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install base packages
      apt: name={{ item }} update_cache=yes
      with_items:
        - python
        - python-pip

    - name: Install pip requirements
      pip:
        name: "{{ item }}"
        state: latest
        executable: pip
      with_items:
        - pip

- name: install docker
  hosts: all
  become_user: root
  become: yes
  roles:
    - ansible-docker-role
